modLoader="javafml"
loaderVersion="[45,)"
license = "GPL-2.0"
issueTrackerURL = "https://github.com/Hojosa/Relics/issues"

[[mods]]
	modId = "relics"
	version = "0.4"
	displayName = "Relics"
	logoFile = ""
	credits = ""
	authors = "Hojosa"
	description = '''
	'''

[[dependencies.relics]] #optional
	modId = "forge"
	mandatory = true
	versionRange = "[45,)"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.relics]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.20.1,1.20.2)"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.relics]]
    modId="mantle"
    mandatory=true
    versionRange="${mantle_range}"
    ordering="NONE"
    side="BOTH"

 [[dependencies.relics]]
    modId="jei"
    mandatory=false
    versionRange="${jei_range}"
    ordering="NONE"
    side="BOTH"
    
 [[dependencies.relics]]
    modId="expandability"
    mandatory=true
    versionRange="${expandability_range}"
    ordering="NONE"
    side="BOTH"
    
 [[dependencies.relics]]
    modId="curios"
    mandatory=false
    versionRange="${curios_range}"
    ordering="NONE"
    side="BOTH"