modLoader="javafml"
loaderVersion="[45,)"
license = "GPL-2.0"
issueTrackerURL = "https://github.com/Hojosa/Relics/issues"

[[mods]]
	modId = "${mod_id}"
	version = "${mod_version}"
	displayName = "${mod_name}"
	logoFile = ""
	credits = ""
	authors = "${mod_authors}"
	description = '''${mod_description}'''

[[dependencies.${mod_id}]]
	modId = "forge"
	mandatory = true
	versionRange = "${forge_version_range}"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.${mod_id}]]
	modId = "minecraft"
	mandatory = true
	versionRange = "${minecraft_version_range}"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.${mod_id}]]
    modId="mantle"
    mandatory=true
    versionRange="${mantle_range}"
    ordering="NONE"
    side="BOTH"

 [[dependencies.${mod_id}]]
    modId="jei"
    mandatory=false
    versionRange="${jei_range}"
    ordering="NONE"
    side="BOTH"
    
 [[dependencies.${mod_id}]]
    modId="expandability"
    mandatory=true
    versionRange="${expandability_range}"
    ordering="NONE"
    side="BOTH"
    
 [[dependencies.${mod_id}]]
    modId="curios"
    mandatory=true
    versionRange="${curios_range}"
    ordering="NONE"
    side="BOTH"