name: Build & Publish Mod

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Gradle
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: Publish Mod
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: build/libs/!(*-@(dev|sources|javadoc)).jar

          modrinth-id: nIS3DCHl
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 1255041
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
